export const GET_APPOINTMENT = 'GET_APPOINTMENT';
export const GET_APPOINTMENT_OK = 'GET_APPOINTMENT_OK';
export const GET_APPOINTMENT_ERROR = 'GET_APPOINTMENT_ERROR';
export const POST_APPOINTMENT = 'POST_APPOINTMENT';
export const POST_APPOINTMENT_OK = 'POST_APPOINTMENT_OK';
export const POST_APPOINTMENT_ERROR = 'POST_APPOINTMENT_ERROR';